import { Router } from 'express';
import { runBacktest } from '../services/backtester.js';
import { analyzeAndOptimize } from '../services/optimizer.js';
import { runWalkForward } from '../services/walkForward.js';
import { runMonteCarlo } from '../services/monteCarlo.js';
import { getATRVolatilityState } from '../services/adaptiveATR.js';

const router = Router();

/**
 * POST /api/backtest/run
 * Runs backtest with given parameters.
 * Body: { symbol, interval, limit, rsiUp, rsiDown, volMin, slRatio, tpRatio }
 */
router.post('/run', async (req, res) => {
  try {
    const {
      symbol   = 'BTC-USDT',
      interval = '5m',
      limit    = 300,
      rsiUp    = parseFloat(process.env.RSI_UP      ?? 55),
      rsiDown  = parseFloat(process.env.RSI_DOWN    ?? 45),
      volMin   = parseFloat(process.env.VOL_REL_MIN ?? 1.2),
      slRatio  = 1.0,
      tpRatio  = 2.0,
    } = req.body;

    console.log(`[Backtest] Running ${symbol} ${interval} x${limit} candles`);
    const result = await runBacktest({ symbol, interval, limit: Math.min(limit, 1000), rsiUp, rsiDown, volMin, slRatio, tpRatio });
    res.json({ ok: true, ...result });
  } catch (err) {
    console.error('[Backtest] Error:', err.message);
    res.status(500).json({ ok: false, error: err.message });
  }
});

/**
 * POST /api/backtest/optimize
 * Runs backtest + analysis + suggestions.
 * Body: { symbol, interval, limit }
 */
router.post('/optimize', async (req, res) => {
  try {
    const { symbol = 'BTC-USDT', interval = '5m', limit = 300 } = req.body;
    console.log(`[Optimizer] Analyzing ${symbol} ${interval}`);
    const result = await analyzeAndOptimize({ symbol, interval, limit: Math.min(limit, 1000) });
    res.json({ ok: true, ...result });
  } catch (err) {
    console.error('[Optimizer] Error:', err.message);
    res.status(500).json({ ok: false, error: err.message });
  }
});

/**
 * POST /api/backtest/walk-forward
 * Runs walk-forward testing to detect overfitting.
 * Body: { symbol, interval, folds, trainSize, testSize, rsiUp, rsiDown, volMin }
 */
router.post('/walk-forward', async (req, res) => {
  try {
    const {
      symbol    = 'BTC-USDT',
      interval  = '5m',
      folds     = 5,
      trainSize = 200,
      testSize  = 100,
      rsiUp     = parseFloat(process.env.RSI_UP      ?? 55),
      rsiDown   = parseFloat(process.env.RSI_DOWN    ?? 45),
      volMin    = parseFloat(process.env.VOL_REL_MIN ?? 1.2),
    } = req.body;

    console.log(`[WalkForward] Request for ${symbol} ${interval} — ${folds} folds`);
    const result = await runWalkForward({
      symbol,
      interval,
      folds,
      trainSize,
      testSize,
      rsiUp,
      rsiDown,
      volMin,
    });
    res.json({ ok: true, ...result });
  } catch (err) {
    console.error('[WalkForward] Error:', err.message);
    res.status(500).json({ ok: false, error: err.message });
  }
});

/**
 * POST /api/backtest/monte-carlo
 * Runs Monte Carlo simulation on backtest results.
 * First runs backtest to get trades, then runs Monte Carlo with those trades.
 * Body: { symbol, interval, limit, rsiUp, rsiDown, volMin, simulations, ruinThreshold }
 */
router.post('/monte-carlo', async (req, res) => {
  try {
    const {
      symbol        = 'BTC-USDT',
      interval      = '5m',
      limit         = 500,
      rsiUp         = parseFloat(process.env.RSI_UP      ?? 55),
      rsiDown       = parseFloat(process.env.RSI_DOWN    ?? 45),
      volMin        = parseFloat(process.env.VOL_REL_MIN ?? 1.2),
      simulations   = 1000,
      ruinThreshold = 20,
    } = req.body;

    console.log(`[MonteCarlo] Request for ${symbol} ${interval} — ${simulations} simulations`);

    // First, run backtest to get trades
    const backtestResult = await runBacktest({
      symbol,
      interval,
      limit: Math.min(limit, 1000),
      rsiUp,
      rsiDown,
      volMin,
    });

    if (!backtestResult.trades || backtestResult.trades.length === 0) {
      return res.json({
        ok: true,
        backtest: backtestResult.metrics,
        monteCarlo: {
          simulations: 0,
          pnlDistribution: { p5: 0, p25: 0, p50: 0, p75: 0, p95: 0 },
          drawdownDistribution: { p5: 0, p25: 0, p50: 0, p75: 0, p95: 0 },
          ruinProbability: 0,
          verdict: 'No trades generated by backtest — cannot run Monte Carlo.',
        },
      });
    }

    // Run Monte Carlo on the trades
    const mcResult = runMonteCarlo({
      trades:        backtestResult.trades,
      simulations,
      ruinThreshold,
    });

    res.json({
      ok: true,
      backtest: backtestResult.metrics,
      monteCarlo: mcResult,
    });
  } catch (err) {
    console.error('[MonteCarlo] Error:', err.message);
    res.status(500).json({ ok: false, error: err.message });
  }
});

/**
 * GET /api/backtest/atr-state
 * Returns the current adaptive ATR volatility state.
 */
router.get('/atr-state', (_req, res) => {
  const state = getATRVolatilityState();

  if (!state) {
    return res.json({
      ok: true,
      state: null,
      message: 'Adaptive ATR not yet calculated. Will be available after first hourly recalc.',
    });
  }

  res.json({ ok: true, state });
});

export { router };
